### ISSUE TITLE
Support PHP 7.1

### ISSUE THREAD

**Issue by alanheppenstall** [accredible/accredible-certificates#3]
https://wordpress.org/support/topic/cant-setting-2/

Fatal error: Uncaught ArgumentCountError: Too few arguments to function do_settings_fields(), 1 passed in C:\xampp\htdocs\wordpress-three\wp-content\plugins\accredible-certificates\templates\settings.php on line 5 and exactly 2 expected in C:\xampp\htdocs\wordpress-three\wp-admin\includes\template.php:1343 Stack trace: #0 C:\xampp\htdocs\wordpress-three\wp-content\plugins\accredible-certificates\templates\settings.php(5): do_settings_fields(‘accredible_cert…’) #1 C:\xampp\htdocs\wordpress-three\wp-content\plugins\accredible-certificates\settings.php(125): include(‘C:\\xampp\\htdocs…’) #2 C:\xampp\htdocs\wordpress-three\wp-includes\class-wp-hook.php(298): Accredible_Certificates_Settings->plugin_settings_page(”) #3 C:\xampp\htdocs\wordpress-three\wp-includes\class-wp-hook.php(323): WP_Hook->apply_filters(”, Array) #4 C:\xampp\htdocs\wordpress-three\wp-includes\plugin.php(453): WP_Hook->do_action(Array) #5 C:\xampp\htdocs\wordpress-three\wp-admin\admin.php(222): do_action(‘settings_page_a…’) #6 C:\xampp\htdocs\wordp in C:\xampp\htdocs\wordpress-three\wp-admin\includes\template.php on line 1343

**Comment by alanheppenstall** [comment]
This *should* be resolved in version 1.2.0.
